#!/bin/bash
# =============================================================================
# update-structure.sh — Auto-update STRUCTURE.md on structural changes
# =============================================================================
# Triggered by PostToolUse hook on Write|Edit|Bash
# Filters to only regenerate on actual structural changes
# =============================================================================

set -euo pipefail

# Read input from Claude Code
INPUT=$(cat)
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // ""')
COMMAND=$(echo "$INPUT" | jq -r '.tool_input.command // ""')
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // ""')

# -----------------------------------------------------------------------------
# Filter: Only trigger on structural changes
# -----------------------------------------------------------------------------

if [[ "$TOOL_NAME" == "Bash" ]]; then
  # Only trigger on directory/file structure commands
  if [[ ! "$COMMAND" =~ (mkdir|mv|rm|cp|touch|rmdir) ]]; then
    exit 0
  fi
elif [[ "$TOOL_NAME" == "Write" ]]; then
  # New file creation — structural change
  : # Continue to regenerate
elif [[ "$TOOL_NAME" == "Edit" ]]; then
  # File edit — not structural, skip
  exit 0
else
  # Unknown tool, skip
  exit 0
fi

# Don't trigger on STRUCTURE.md itself (avoid infinite loop)
if [[ "$FILE_PATH" == *"STRUCTURE.md"* ]]; then
  exit 0
fi

# -----------------------------------------------------------------------------
# Regenerate STRUCTURE.md
# -----------------------------------------------------------------------------

cd "$CLAUDE_PROJECT_DIR" || exit 0

# Generate new STRUCTURE.md
cat > STRUCTURE.md << 'EOF'
# STRUCTURE.md — Auto-Generated

> **This file is automatically updated by Claude Code hooks.**
> Do not edit manually — changes will be overwritten.

EOF

# Add timestamp
echo "**Last updated**: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> STRUCTURE.md
echo "" >> STRUCTURE.md
echo "---" >> STRUCTURE.md
echo "" >> STRUCTURE.md

# Add tree output
echo '```' >> STRUCTURE.md
tree -a -I '.git' --dirsfirst -L 4 -F 2>/dev/null >> STRUCTURE.md || echo "tree command not available"
echo '```' >> STRUCTURE.md

# Add stats
echo "" >> STRUCTURE.md
echo "---" >> STRUCTURE.md
echo "" >> STRUCTURE.md
echo "_Generated by \`.claude/hooks/update-structure.sh\`_" >> STRUCTURE.md

exit 0
